kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "pxc-operator.fullname" . }}
  labels:
{{ include "pxc-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "pxc-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "pxc-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
