{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pxc-operator.serviceAccountName" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "pxc-operator.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}